### ISSUE TITLE
For German "errorLoading" error function is missing

### ISSUE THREAD

**Issue by nagarjunayadavk** [argerim/select2-rails#189]
Hi,

I am facing issue with I18n for German language for **errorLoading** message and it's showing in English. 

as per my analysis   **errorLoading** function is is missing from **select2_locale_de.js.** file.
Please update.

![image](https://user-images.githubusercontent.com/3591072/60800246-86c70d80-a192-11e9-8131-c23fe1ee2cf8.png)

**Comment by ghost** [comment]
@nagarjunayadavk This issue should be opened with the select2 project (https://github.com/select2/select2). I have created tags for all missing select2 versions here, your issue might have been resolved in one of those new releases. Feel free to reopen this if you do find your problem is related to how we package the select2 js.
